---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: tautulli
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.2.133"
spec:
  selector:
    app: tautulli
  ports:
  - name: http
    port: 8181
    targetPort: 8181
    protocol: TCP
  type: LoadBalancer
