---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
  annotations:
spec:
  entryPoints:
  - websecure
  routes:
  # WebSocket notifications (must come first due to more specific path)
  - match: Host(`vault.tehmatt.com`) && Path(`/notifications/hub`)
    kind: Rule
    services:
    - name: vaultwarden
      port: 3012
      passHostHeader: false
    middlewares:
    - name: default-headers
      namespace: vaultwarden
  # Main HTTP UI/API
  - match: Host(`vw.tehmatt.com`)
    kind: Rule
    services:
    - name: vaultwarden
      port: 80
      passHostHeader: false
    middlewares:
    - name: default-headers
      namespace: vaultwarden
  tls:
    secretName: tehmatt-tls # TODO: change if needed
