apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-image-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-image-updater
subjects:
  - kind: ServiceAccount
    name: k8s-image-updater
    namespace: image-updater
