---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: loki
  namespace: loki-stack
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`loki.tehmatt.com`)
    kind: Rule
    services:
    - name: loki
      port: 3100
      passHostHeader: false
    middlewares:
    - name: default-headers
  tls: {}
