apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki-stack

resources:
  - _namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml
  - default-headers.yaml
  - promtail-rbac.yaml
  - promtail-configmap.yaml
  - promtail-daemonset.yaml
