apiVersion: v1
kind: Secret
metadata:
  name: avp-config
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/name: avp-config
    argocd.argoproj.io/secret-type: argocd-vault-plugin
stringData:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: kubernetes
  VAULT_ADDR: https://vault.tehmatt.com
  AVP_KUBERNETES_ROLE: argocd
  AVP_KUBERNETES_TOKEN_PATH: /var/run/secrets/tokens/vault-token
  AVP_LOG_LEVEL: info
