apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

# Pin to a specific Argo CD version
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.2.6/manifests/install.yaml
- avp-plugin.yaml
- ingress.yaml
- apps/audiobookshelf.yaml
- apps/mealie.yaml
- apps/notifiarr.yaml
- apps/vaultwarden.yaml

patchesStrategicMerge:
- patch-repo-server-avp.yaml

patches:
- target:
    kind: Deployment
    name: argocd-server
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args
      value: ["--insecure"]
- target:
    kind: Service
    name: argocd-server
  patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer
