apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      automountServiceAccountToken: true
      imagePullSecrets:
      - name: ghcr-cred
      volumes:
      - name: custom-tools
        emptyDir: {}
      - name: k8s-sa-token
        projected:
          sources:
          - serviceAccountToken:
              audience: vault
              path: vault-token
              expirationSeconds: 7200
      - name: cmp-avp
        configMap:
          name: argocd-cmp-avp
      initContainers:
      - name: download-avp
        image: curlimages/curl:8.10.1
        imagePullPolicy: IfNotPresent
        env:
        - name: AVP_VERSION
          value: "1.13.1"
        command: [ "sh", "-lc" ]
        args:
        - >-
          curl -L "https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64" -o /custom-tools/argocd-vault-plugin && chmod +x /custom-tools/argocd-vault-plugin
        volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools
      containers:
      - name: avp
        image: alpine:3.20
        imagePullPolicy: IfNotPresent
        command: [ "/var/run/argocd/argocd-cmp-server" ]
        securityContext:
          runAsUser: 999
          runAsGroup: 999
        env:
        - name: AVP_TYPE
          value: vault
        - name: AVP_AUTH_TYPE
          value: k8s
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: argocd-cmp-avp
              key: vaultAddr
        - name: AVP_KUBERNETES_ROLE
          valueFrom:
            configMapKeyRef:
              name: argocd-cmp-avp
              key: kubernetesRole
        - name: AVP_K8S_ROLE
          valueFrom:
            configMapKeyRef:
              name: argocd-cmp-avp
              key: kubernetesRole
        - name: AVP_KUBERNETES_TOKEN_PATH
          value: /var/run/secrets/tokens/vault-token
        - name: AVP_K8S_TOKEN_PATH
          value: /var/run/secrets/tokens/vault-token
        - name: AVP_LOG_LEVEL
          value: info
        volumeMounts:
        - name: var-files
          mountPath: /var/run/argocd
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
        - name: k8s-sa-token
          mountPath: /var/run/secrets/tokens
        - name: cmp-avp
          mountPath: /home/argocd/cmp-server/config
          readOnly: true
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
