apiVersion: apps/v1
kind: Deployment
metadata:
  name: dozzle
  namespace: dozzle
spec:
  selector:
    matchLabels:
      app: dozzle
  template:
    metadata:
      labels:
        app: dozzle
    spec:
      nodeSelector:
        worker: "true"
      serviceAccountName: pod-viewer
      containers:
      - name: dozzle
        image: amir20/dozzle:v9.0.3
        ports:
        - containerPort: 8080
        env:
        - name: DOZZLE_MODE
          value: "k8s"
