apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: notifiarr
  namespace: notifiarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`notifiarr.tehmatt.com`)
      kind: Rule
      services:
        - name: notifiarr
          port: 5454
      middlewares:
        - name: default-headers
          namespace: notifiarr
  tls: {}
