apiVersion: v1
kind: Service
metadata:
  name: plex-exporter
  namespace: prometheus
  labels:
    app: plex-exporter
spec:
  type: ClusterIP
  selector:
    app: plex-exporter
  ports:
  - name: metrics
    port: 9000
    targetPort: 9000
    protocol: TCP
