apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebridge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mtstrong/homelab.git
    targetRevision: main
    path: kubernetes/homebridge
  destination:
    server: https://kubernetes.default.svc
    namespace: homebridge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
