apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/name: it-tools
spec:
  project: default
  source:
    repoURL: https://github.com/mtstrong/homelab.git
    path: kubernetes/it-tools
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: it-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
