apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notifiarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mtstrong/homelab.git
    targetRevision: main
    path: kubernetes/notifiarr
  destination:
    server: https://kubernetes.default.svc
    namespace: notifiarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
