apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readarr
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/name: readarr
spec:
  project: default
  source:
    repoURL: https://github.com/mtstrong/homelab.git
    path: kubernetes/readarr
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: readarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
