---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mtstrong/homelab.git
    targetRevision: HEAD
    path: kubernetes/sabnzbd
  destination:
    server: https://kubernetes.default.svc
    namespace: sabnzbd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
