---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mtstrong/homelab.git
    targetRevision: HEAD
    path: kubernetes/tautulli
  destination:
    server: https://kubernetes.default.svc
    namespace: tautulli
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
