apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mtstrong/homelab.git
    targetRevision: main
    path: kubernetes/k8s-image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: image-updater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: github-token
      namespace: image-updater
