apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - _namespace.yml
  - datasources.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - default-headers.yaml
  - dashboard-provider.yaml
  - dashboard-plex-enhanced.yaml
  - dashboard-technotim-plex.yaml
  - grafana-dashboard-finops.yaml
