---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: overseerr
spec:
  ports:
  - port: 5055
    targetPort: 5055
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: overseerr
  namespace: overseerr
subsets:
- addresses:
  - ip: 192.168.1.37 # Docker host IP
  ports:
  - port: 5055
